version: "3"

services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        environment:
            - DATABASE_URL=postgresql://user:pass@postgres_db:5432/my_db
            - DB_ECHO_LOG=1
        ports:
            - "8001:8080"

    postgres_db:
        image: bitnami/postgresql:latest
        environment:
            - POSTGRESQL_USERNAME=user
            - POSTGRESQL_PASSWORD=pass
            - POSTGRESQL_DATABASE=my_db
        ports:
            - "5434:5432"
